version: '3.2'
services:
  backend:
    build: Backend
    ports:
      - 8005:8005
    volumes:
      - type: bind
        source: ./Backend/data/choices.csv
        target: /data/choices.csv
      - type: bind
        source: ./Backend/models/w2v_spec.pkl
        target: /models/w2v_spec.pkl
  frontend:
    build: Frontend
    ports:
      - 80:8000
